WITH PRODUCT_UNIQUE AS (
    SELECT DISTINCT MENU_TYPE_ID, TRUCK_BRAND_NAME
    FROM {{ ref('l1_product') }}
),
l2_dim_truck AS (
    SELECT
        TRUCK.TRUCK_ID,
        PRODUCT.TRUCK_BRAND_NAME,
        TRUCK.CAR_BRAND, 
        TRUCK.MODEL,
        TRUCK.YEAR
    FROM {{ ref('l1_truck') }} TRUCK
    LEFT JOIN PRODUCT_UNIQUE PRODUCT 
    ON PRODUCT.MENU_TYPE_ID = TRUCK.MENU_TYPE_ID
)
SELECT
    TRUCK_ID,
    TRUCK_BRAND_NAME,
    CAR_BRAND,
    MODEL,
    YEAR
FROM l2_dim_truck
