WITH SRC AS (
    SELECT * FROM {{ source('pos', 'menu') }}
),
TRANSFORMED AS (
SELECT
    MENU_ID,
    MENU_ITEM_ID AS PRODUCT_ID,
    MENU_ITEM_NAME AS PRODUCT_NAME,
    ITEM_CATEGORY AS PRODUCT_CATEGORY, 
    ITEM_SUBCATEGORY AS PRODUCT_SUBCATEGORY,
    MENU_TYPE,
    MENU_TYPE_ID,
    SALE_PRICE_USD,
    COST_OF_GOODS_USD,
    TRUCK_BRAND_NAME,
    MENU_ITEM_HEALTH_METRICS_OBJ
FROM SRC
)

SELECT * FROM TRANSFORMED