WITH SRC AS (
    SELECT * FROM {{ source('pos', 'order_detail') }}
),
TRANSFORMED AS (
SELECT
    ORDER_DETAIL_ID,
    ORDER_ID,
    MENU_ITEM_ID AS PRODUCT_ID,
    LINE_NUMBER,
    DISCOUNT_ID,
    ORDER_ITEM_DISCOUNT_AMOUNT,
    PRICE,
    QUANTITY,
    UNIT_PRICE
FROM SRC
)

SELECT * FROM TRANSFORMED